const Us={
  ZH: {  //中文翻译
      p1: "The Belt and Road Initiative International Union for Anatomists (BRIIUA) is established under the guidance of the Chinese Association for Science and Technology, initiated by the Chinese Society of Anatomy and assisted by the Guangxi Society of Anatomy. Enterprises jointly build a new pattern of scientific and technological exchanges featuring in-depth integration, open cooperation, mutual benefit and win-win results, and promote the resolution of major issues in the field of global health and development.",
      p2: "The BRIIUA adheres to the principles of mutual respect, academic democracy, mutual assistance, mutual benefit, and self-volunteership. It takes truth-seeking, innovation, collaboration, and dedication as its purpose, and upholds the Silk Road spirit of peaceful cooperation, openness and tolerance, mutual learning, mutual benefit and win-win, and builds an international society. The characteristic platform for scientific and technological cooperation and exchange has established a long-term interdisciplinary science and humanities exchange mechanism under the background of new medical sciences, and has made positive contributions to the advancement of anatomical science and technology innovation and the promotion of human health.",
      p3: 'BRIIUA aims to build a characteristic platform for international scientific and technological exchanges and cooperation under the "One Belt One Road" initiative. Focusing on the overall goal of building a "technological community", international conferences with the theme of scientific and technological innovation are regularly held every year, and efforts are made to make them an influential international anatomy research academic exchange event; in technological innovation, scientific research, and achievement transformation, etc. To carry out extensive multilateral exchanges to promote collaborative innovation in medical research in alliance member countries and regions.',
      p4:'BRIIUA will focus on the overall goal of building a "community with a shared future for the development of anatomy", combined with Guangxi as an important gateway for the organic connection of the "Belt and Road" and its radiating and leading role in Southeast Asia, building a long-term interdisciplinary science and technology and humanistic exchange in the context of new medical sciences Mechanism, to make a positive contribution to the advancement of anatomical technology innovation and the promotion of human health.',
      p5:'BRIIUA will also be committed to promoting the sharing of development opportunities among member units and expanding cooperation fields. The alliance will uphold the Silk Road spirit of peaceful cooperation, openness and tolerance, mutual learning, mutual benefit and win-win as the core, and actively promote the "Belt and Road". National scientific and technological consensus and cooperation, improve multilateral cultural exchanges and cooperation, and actively build a characteristic platform for international scientific and technological cooperation and exchanges under the “Belt and Road” initiative. Play a constructive role in promoting the understanding and mutual trust, exchanges and cooperation, and scientific development and progress of people in different countries and regions.',
    },
  EN: {  //英文翻译
    p1: "The Belt and Road Initiative International Union for Anatomists (BRIIUA) is established under the guidance of the Chinese Association for Science and Technology, initiated by the Chinese Society of Anatomy and assisted by the Guangxi Society of Anatomy. Enterprises jointly build a new pattern of scientific and technological exchanges featuring in-depth integration, open cooperation, mutual benefit and win-win results, and promote the resolution of major issues in the field of global health and development.",
    p2: "The BRIIUA adheres to the principles of mutual respect, academic democracy, mutual assistance, mutual benefit, and self-volunteership. It takes truth-seeking, innovation, collaboration, and dedication as its purpose, and upholds the Silk Road spirit of peaceful cooperation, openness and tolerance, mutual learning, mutual benefit and win-win, and builds an international society. The characteristic platform for scientific and technological cooperation and exchange has established a long-term interdisciplinary science and humanities exchange mechanism under the background of new medical sciences, and has made positive contributions to the advancement of anatomical science and technology innovation and the promotion of human health.",
    p3: 'BRIIUA aims to build a characteristic platform for international scientific and technological exchanges and cooperation under the "One Belt One Road" initiative. Focusing on the overall goal of building a "technological community", international conferences with the theme of scientific and technological innovation are regularly held every year, and efforts are made to make them an influential international anatomy research academic exchange event; in technological innovation, scientific research, and achievement transformation, etc. To carry out extensive multilateral exchanges to promote collaborative innovation in medical research in alliance member countries and regions.',
    p4:'BRIIUA will focus on the overall goal of building a "community with a shared future for the development of anatomy", combined with Guangxi as an important gateway for the organic connection of the "Belt and Road" and its radiating and leading role in Southeast Asia, building a long-term interdisciplinary science and technology and humanistic exchange in the context of new medical sciences Mechanism, to make a positive contribution to the advancement of anatomical technology innovation and the promotion of human health.',
    p5:'BRIIUA will also be committed to promoting the sharing of development opportunities among member units and expanding cooperation fields. The alliance will uphold the Silk Road spirit of peaceful cooperation, openness and tolerance, mutual learning, mutual benefit and win-win as the core, and actively promote the "Belt and Road". National scientific and technological consensus and cooperation, improve multilateral cultural exchanges and cooperation, and actively build a characteristic platform for international scientific and technological cooperation and exchanges under the “Belt and Road” initiative. Play a constructive role in promoting the understanding and mutual trust, exchanges and cooperation, and scientific development and progress of people in different countries and regions.',
  }
}
export default Us  //需要暴露出去