const Home={
  ZH: {  //中文翻译
      p1: "“一带一路” 国际解剖学联盟（The Belt and Road Initiative International Union for Anatomists,简称BRIIUA）。是在中国科协的指导下，由中国解剖学会作发起组建、广西解剖学会协助组建的，旨在与“一带一路”沿线国家和地区的解剖学相关领域医学院校、科研院所、科技创新企业共同建设深度融合、开放合作、互利共赢的科技交流新格局，推动解决全球健康与发展领域的重大问题。",
      p2: "BRIIUA联盟坚持相互尊重、学术民主、互助互利、自主自愿的原则，以求实、创新、协作、奉献为宗旨，秉持和平合作、开放包容、互学互鉴、互利共赢的丝路精神，打造国际科技合作与交流特色平台，建构起新医科背景下的跨学科科技与人文长效交流机制，为推进解剖学科技创新和促进人类健康作出积极的贡献。",
      p3: "BRIIUA旨在搭建“一带一路”国际科技交流与合作的特色平台。围绕构建“科技共同体”的总体目标，每年定期举办以科技创新为主题的国际会议，并着力将其打造成有影响力的国际解剖学研究学术交流盛会；在技术创新、科学研究、成果转化等方面广泛开展多边交流，推动联盟成员国家和地区的医学研究协同创新。",
      p4:'BRIIUA将围绕构建“解剖学发展命运共同体”的总体目标，结合广西作为“一带一路”有机衔接的重要门户以及对东南亚的辐射带动作用，建构起新医科背景下的跨学科科技与人文长效交流机制，为推进解剖学科技创新和促进人类健康作出积极的贡献。',
      p5:'BRIIUA还将致力于促进成员单位间共享发展机遇，拓展合作领域，联盟将秉持以和平合作、开放包容、互学互鉴、互利共赢为核心的丝路精神，积极推进与“一带一路”沿线国家的科技共识与协作，健全多边人文交流与合作，积极打造“一带一路”国际科技合作与交流特色平台。为促进不同国家和地区之间人民的理解与互信、交流与合作、科学的发展与进步发挥建设性作用。',
      p6:'2013年，中国国家主席习近平提出了“一带一路” 倡议，该倡议包括丝绸之路经济带和二十一世纪海上丝绸之路（简称一带一路），旨在建立一个沿古代商贸路线连接亚洲、欧洲和非洲的贸易和基础设施网络。为积极推动国家“一带一路”倡议，深化与沿线国家之间的医学研究交流，携手共建“健康丝绸之路”，由中国科协指导，中国解剖学会主办，广西医科大学和广西解剖学会承办的“一带一路”国际解剖学联盟学术会议将于2021年12月11日-12月13日通过“线上+线下”相结合的方式在南宁市沃顿国际大酒店三楼北京厅隆重举行。',
      p7:'本次大会以“人体解剖学与临床医学”为主题，已邀请近40位来自世界各地解剖学、生物学、遗传学、临床医学等领域的知名专家学者围绕前沿进展进行深入探讨与交流。这将是一次具有影响力的高水平学术盛会和经验交流会，将为推动建设科学研究及创新教学方法等方面的国际合作体系、建构新医科背景下的跨学科科技与人文长效交流机制、推进科技创新、发现和培养优秀青年人才以及促进人类健康作出积极的贡献。',
    },
  EN: {  //英文翻译
      p1: "The Belt and Road Initiative International Union for Anatomists (BRIIUA) is established under the guidance of the Chinese Association for Science and Technology, initiated by the Chinese Society of Anatomy and assisted by the Guangxi Society of Anatomy. Enterprises jointly build a new pattern of scientific and technological exchanges featuring in-depth integration, open cooperation, mutual benefit and win-win results, and promote the resolution of major issues in the field of global health and development.",
      p2: "The BRIIUA adheres to the principles of mutual respect, academic democracy, mutual assistance, mutual benefit, and self-volunteership. It takes truth-seeking, innovation, collaboration, and dedication as its purpose, and upholds the Silk Road spirit of peaceful cooperation, openness and tolerance, mutual learning, mutual benefit and win-win, and builds an international society. The characteristic platform for scientific and technological cooperation and exchange has established a long-term interdisciplinary science and humanities exchange mechanism under the background of new medical sciences, and has made positive contributions to the advancement of anatomical science and technology innovation and the promotion of human health.",
      p3:'BRIIUA aims to build a characteristic platform for international scientific and technological exchanges and cooperation under the "One Belt One Road" initiative. Focusing on the overall goal of building a "technological community", international conferences with the theme of scientific and technological innovation are regularly held every year, and efforts are made to make them an influential international anatomy research academic exchange event; in technological innovation, scientific research, and achievement transformation, etc. To carry out extensive multilateral exchanges to promote collaborative innovation in medical research in alliance member countries and regions.',
      p4:'BRIIUA will focus on the overall goal of building a "community with a shared future for the development of anatomy", combined with Guangxi as an important gateway for the organic connection of the "Belt and Road" and its radiating and leading role in Southeast Asia, building a long-term interdisciplinary science and technology and humanistic exchange in the context of new medical sciences Mechanism, to make a positive contribution to the advancement of anatomical technology innovation and the promotion of human health.',
      p5:'BRIIUA will also be committed to promoting the sharing of development opportunities among member units and expanding cooperation fields. The alliance will uphold the Silk Road spirit of peaceful cooperation, openness and tolerance, mutual learning, mutual benefit and win-win as the core, and actively promote the "Belt and Road". National scientific and technological consensus and cooperation, improve multilateral cultural exchanges and cooperation, and actively build a characteristic platform for international scientific and technological cooperation and exchanges under the “Belt and Road” initiative. Play a constructive role in promoting the understanding and mutual trust, exchanges and cooperation, and scientific development and progress of people in different countries and regions.',
      p6:'In 2013, Chinese President Xi Jinping raised the initiative of jointly building the Silk Road Economic Belt and the 21st Century Maritime Silk Road (abbreviated as the Belt and Road). It is designed to build trade and infrastructural networks connecting Asian, European, and African countries along the Belt and Road following ancient commercial and trade routes. To actively participate in and promote the national “Belt and Road Initiative”, deepen medical research exchanges among countries along the Belt and Road, and jointly build the "Health Silk Road”, The Belt and Road Initiative International Union for Anatomists Congress will be held in Nanning, capital of the Guangxi Zhuang Autonomous Region, on December 11-13, 2021. On site presentations or online Zoom meetings are available for this conference. ',
      p7:'This congress is sponsored by the China Association for Science and Technology, hosted by the Chinese Society for Anatomical Sciences, and co-organized by Guangxi Medical University and Guangxi Society for Anatomical Sciences, with the theme of “Integration of Human Anatomy with Clinical Medicine”. Approximately 40 renowned scholars and experts with major in anatomy, biology, genetics, and clinical medicine from all over the world have been cordially invited to participate in this event. It will provide an influential forum for exchanging academic progress and experimental expertise, bringing together international collaborations on quality research and novel teaching methods, building interdisciplinary exchanges on science and technology and human cultural features under new dimensions of clinical medicine, and ultimately will contribute greatly to academic innovations, training of young talents, and promoting human health.',
    }
}
export default Home  //需要暴露出去